---
## \file
# \date 2024
# \copyright ItSANgo@gmail.com
# SPDX-License-Identifier: AGPL-3.0-or-later
- name: Setup WSL
  hosts: localhost
  tasks:
    - name: Update APT
      become: true
      ansible.builtin.apt:
        name: "*"
    - name: Install packages
      become: true
      ansible.builtin.apt:
        name:
          - ansible-lint
          - zip
          - unzip
          - gcc
          - g++
          - gcc-14
          - g++-14
          - make
          - byacc
          - bison
          - flex
          - cmake
          - cmake-format
          - shellcheck
          - adr-tools
          - pwgen
          - strace
    - name: Install NVM
      block:
        - name: Create the temporary file name for NVM
          ansible.builtin.tempfile:
          register: nvm_installer
        - name: Get NVM
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh
            dest: "{{ nvm_installer.path }}"
            mode: '700'
        - name: Run NVM installer
          ansible.builtin.command:
            cmd: "{{ nvm_installer.path }}"
          register: result
          changed_when: result.rc != 0
    - name: Install SDKMAN
      block:
        - name: Create the temporary file name for SDKMAN
          ansible.builtin.tempfile:
          register: sdkman_installer
        - name: Get SDKMAN
          ansible.builtin.get_url:
            url: https://get.sdkman.io
            dest: "{{ sdkman_installer.path }}"
            mode: '700'
        - name: Run SDKMAN installer
          ansible.builtin.command:
            cmd: "{{ sdkman_installer.path }}"
          register: result
          changed_when: result.rc != 0
    - name: Install Perlbrew
      block:
        - name: Create the temporary file name for Perlbrew
          ansible.builtin.tempfile:
          register: perlbrew_installer
        - name: Get Perlbrew
          ansible.builtin.get_url:
            url: https://install.perlbrew.pl
            dest: "{{ perlbrew_installer.path }}"
            mode: '700'
        - name: Run Perlbrew installer
          ansible.builtin.command:
            cmd: "{{ perlbrew_installer.path }}"
          register: result
          changed_when: result.rc != 0
        - name: Remove Perlbrew in ~/.bashrc
          ansible.builtin.lineinfile:
            path: ~/.bashrc
            search_string: '~/perl5/perlbrew/etc/bashrc'
            state: absent
        - name: Add Perlbrew to ~/.bashrc
          ansible.builtin.lineinfile:
            path: ~/.bashrc
            line: '[[ -r ~/perl5/perlbrew/etc/bashrc ]] && source ~/perl5/perlbrew/etc/bashrc'
...
